version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # - package-ecosystem: "poetry"
  #   directory: "/pyproject"
  #   schedule:
  #     interval: "weekly"
