version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/inspect_utils"
    schedule:
      interval: "weekly"
  # - package-ecosystem: "poetry"
  #   directory: "/pyproject"
  #   schedule:
  #     interval: "weekly"
