# pyproject/pyproject.toml
[tool.poetry]
name = "inspect_utils"
version = "0.1.0"
description = "utils for inspect."
authors = ["Hariharan Thavachelvam <thavaahariharangit@github.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
